[package]
name = "ascii_generator_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
ab_glyph = "0.2.29"
anyhow = "1.0.93"
image = "0.25.5"
imageproc = "0.25.0"
once_cell = "1.20.2"
rayon = "1.10.0"
